// ─────────────────────────────────────────────────────────────────────────────
// IMAGE CONSTANTS
// All images sourced from src/assets/gellery/
//
// PERFORMANCE: the app imports ONLY the optimised `.webp` files generated by
// `scripts/optimize-images.mjs` (run via `npm run optimize:images`, also before
// every build). Each WebP is a resized ~150-250 KB version of the original
// multi-megabyte JPEG, so pages load near-instantly. The generated WebPs live in
// a SEPARATE tree (src/assets/optimized/**) that mirrors the source folders; the
// original photo folders are never bundled because the globs match the
// `optimized/` tree only.
//
// To add/refresh images: drop new photos into the source folders, then run
// `npm run optimize:images` — no component changes needed.
// ─────────────────────────────────────────────────────────────────────────────

// `import: 'default'` makes each glob module value the emitted asset URL string.
// NOTE: Vite's glob parser requires the options to be an inline object literal
// (a shared variable is rejected), so they are repeated on each call.
const groupRaw = import.meta.glob<string>(
  '../assets/optimized/gellery/Group/*.webp', { eager: true, import: 'default' },
);
const shresthoRaw = import.meta.glob<string>(
  '../assets/optimized/gellery/Shrestho Chakraborty/*.webp', { eager: true, import: 'default' },
);
const joyorshiRaw = import.meta.glob<string>(
  '../assets/optimized/gellery/Joyorshi De/*.webp', { eager: true, import: 'default' },
);
const koustavRaw = import.meta.glob<string>(
  '../assets/optimized/gellery/Koustav Adhikari/*.webp', { eager: true, import: 'default' },
);
const manodeepRaw = import.meta.glob<string>(
  '../assets/optimized/gellery/Manodeep Bose/*.webp', { eager: true, import: 'default' },
);
const arkadeepRaw = import.meta.glob<string>(
  '../assets/optimized/gellery/Arkadeep Chakraborty/*.webp', { eager: true, import: 'default' },
);
const aniketRaw = import.meta.glob<string>(
  '../assets/optimized/gellery/Aniket Dutta/*.webp', { eager: true, import: 'default' },
);
const anishRaw = import.meta.glob<string>(
  '../assets/optimized/gellery/Anish Murmu/*.webp', { eager: true, import: 'default' },
);

// OC folder — cover art / promo shot used on the Saddho Nei Amar card
const ocRaw = import.meta.glob<string>(
  '../assets/optimized/OC/*.webp', { eager: true, import: 'default' },
);

// Dedicated hero/story background — a source file literally named "background"
// (e.g. background.jpg → optimised to optimized/**/background.webp). No index
// lookup needed; falls back to a group photo if absent.
const backgroundRaw = import.meta.glob<string>(
  '../assets/optimized/**/background.webp', { eager: true, import: 'default' },
);

// With `import: 'default'`, each glob value is already the URL string.
const toUrls = (raw: Record<string, string>): string[] => Object.values(raw);

// ─────────────────────────────────────────────────────────────────────────────
// GROUPED EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

export const GROUP_PHOTOS: string[] = toUrls(groupRaw);

export const MEMBER_PHOTOS: Record<string, string[]> = {
  SHRESHTHO: toUrls(shresthoRaw),
  JOYORSHI: toUrls(joyorshiRaw),
  KOUSTAV: toUrls(koustavRaw),
  MANODEEP: toUrls(manodeepRaw),
  ARKADEEP: toUrls(arkadeepRaw),
  ANIKET: toUrls(aniketRaw),
  ANISH: toUrls(anishRaw),
};

// ── Per-context member photos — each surface uses a different index ───────────

/** MemberStrip on home page → first available photo */
export const MEMBER_HERO_PHOTO: Record<string, string> = Object.fromEntries(
  Object.entries(MEMBER_PHOTOS).map(([name, photos]) => [name, photos[0] ?? ''])
);

/** MembersPage (/members) → second photo when available, otherwise first */
export const MEMBER_CARD_PHOTO: Record<string, string> = Object.fromEntries(
  Object.entries(MEMBER_PHOTOS).map(([name, photos]) => [
    name,
    photos[1] ?? photos[0] ?? '',
  ])
);

/** StoryPage featured-member panel → third photo when available, fallback chain */
export const MEMBER_STORY_PHOTO: Record<string, string> = Object.fromEntries(
  Object.entries(MEMBER_PHOTOS).map(([name, photos]) => [
    name,
    photos[2] ?? photos[1] ?? photos[0] ?? '',
  ])
);

// All photos flat (used in Gallery — Group photos first, then per-member)
export const ALL_PHOTOS: { src: string; category: string }[] = [
  ...GROUP_PHOTOS.map((src) => ({ src, category: 'Group' })),
  ...Object.entries(MEMBER_PHOTOS).flatMap(([name, photos]) =>
    photos.map((src) => ({ src, category: name }))
  ),
];

// Hero / story background — dedicated "background" image, falls back to a group photo
export const HERO_BG: string = toUrls(backgroundRaw)[0] ?? GROUP_PHOTOS[0] ?? '';

// About section photo — second group photo (or fallback to first)
export const ABOUT_PHOTO: string = GROUP_PHOTOS[1] ?? GROUP_PHOTOS[0] ?? '';

// Experience section photo — third group photo
export const EXPERIENCE_PHOTO: string = GROUP_PHOTOS[2] ?? GROUP_PHOTOS[0] ?? '';

// Cover art / promo image for the Saddho Nei Amar feature card
export const ORIGINAL_PHOTO: string = toUrls(ocRaw)[0] ?? '';

// Gallery filter categories (matches ALL_PHOTOS category values)
export const GALLERY_CATEGORIES: string[] = [
  'All',
  'Group',
  'SHRESHTHO',
  'JOYORSHI',
  'KOUSTAV',
  'MANODEEP',
  'ARKADEEP',
  'ANIKET',
  'ANISH',
];
